[build]
  command = "pnpm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Headers for better caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/image"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for Next.js
[[redirects]]
  from = "/_next/image"
  query = { q = ":quality", url = ":url", w = ":width" }
  status = 200
  to = "/.netlify/images?url=:url&w=:width&q=:quality"

[[redirects]]
  from = "/_ipx/*"
  query = { q = ":quality", url = ":url", w = ":width" }
  status = 200
  to = "/.netlify/images?url=:url&w=:width&q=:quality"

# Configure the Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"
